name: "Setup Dosei CLI"
description: 'Setup dctl (Dosei CLI) in your Github Actions workflow.'
author: doseiai

branding:
  icon: 'box'
  color: 'black'

inputs:
  token:
    description: 'Your Dosei token.'
    required: false

runs:
  using: "composite"
  steps:
    - run: |
        curl -fsSL https://dosei.ai/install.sh | sh
        echo "DOSEI_CLI_INSTALL=/home/runner/.dosei" >> $GITHUB_ENV
        echo "PATH=$DOSEI_CLI_INSTALL/bin:$PATH" >> $GITHUB_ENV
      shell: bash
    - run: echo "DOSEI_TOKEN=${{ inputs.token }}" >> $GITHUB_ENV
      if: ${{ inputs.token }}
      shell: bash
